
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: stackconfigurations.helm.samples.stacks.crossplane.io
spec:
  group: helm.samples.stacks.crossplane.io
  names:
    kind: StackConfiguration
    listKind: StackConfigurationList
    plural: stackconfigurations
    singular: stackconfiguration
  scope: ""
  validation:
    openAPIV3Schema:
      description: StackConfiguration is the Schema for the stackconfigurations API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StackConfigurationSpec defines the desired state of StackConfiguration
          properties:
            behaviors:
              description: 'Important: Run "make" to regenerate code after modifying
                this file'
              properties:
                crds:
                  additionalProperties:
                    description: StackConfigurationBehavior specifies an individual
                      behavior, by listing resources which should be processed.
                    properties:
                      engine:
                        properties:
                          type:
                            type: string
                        required:
                        - type
                        type: object
                      hooks:
                        additionalProperties:
                          items:
                            description: HookConfiguration is the configuration for
                              an individual hook which will be executed in response
                              to an event.
                            properties:
                              directory:
                                type: string
                              engine:
                                properties:
                                  type:
                                    type: string
                                required:
                                - type
                                type: object
                            required:
                            - directory
                            type: object
                          type: array
                        type: object
                    required:
                    - hooks
                    type: object
                  type: object
                engine:
                  properties:
                    type:
                      type: string
                  required:
                  - type
                  type: object
                source:
                  description: Theoretically, source and engine could be specified
                    at a per-crd level or per-hook level as well.
                  properties:
                    image:
                      description: a container image id
                      type: string
                  type: object
              type: object
          type: object
        status:
          description: StackConfigurationStatus defines the observed state of StackConfiguration
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
