apiVersion: apps/v1
kind: Deployment
metadata:
  name: "crossplane-stack-helm"
  labels:
    core.crossplane.io/name: "crossplane-stack-helm"
spec:
  selector:
    matchLabels:
      core.crossplane.io/name: "crossplane-stack-helm"
  replicas: 1
  template:
    metadata:
      name: "crossplane-stack-helm-controller"
      labels:
        core.crossplane.io/name: "crossplane-stack-helm"
    spec:
      containers:
      - name: "crossplane-stack-template-engine-controller"
        image: "crossplane/stack-template-engine"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
